// export const metadata = {
//   title: 'Next.js',
//   description: 'Generated by Next.js',
// }
//
// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode
// }) {
//   return (
//     <html lang="en">
//       <body>{children}</body>
//     </html>
//   )
// }

import {Footer, Layout, Navbar} from "nextra-theme-docs";
import {Banner, Head} from "nextra/components";
import {getPageMap} from "nextra/page-map";
import "nextra-theme-docs/style.css";
import Link from "next/link";

/**
 * @type {Metadata}
 */
export const metadata = {
    // Define your metadata here
    // For more information on metadata API, see: https://nextjs.org/docs/app/building-your-application/optimizing/metadata
    metadataBase: new URL("https://riffy.js.org"),
    title: {
        template: "%s | Riffy",
    },
    description: "Riffy is a pro lavalink client. Designed to be simple and easy to use, with a focus on stability and more features.",
    keywords: ["discord-music-bot", "lavalink", "lavalink client", "lavalink-client", "Riffy", "Riffy Music Bot", "riffyjs"],
    appleWebApp: {
        title: "Riffy"
    },
    generator: "Next.js",
    twitter: {
        site: "https://riffy.js.org",
    }
};

const banner = <Banner storageKey="LL-v3-deprecation-banner">
    <Link href="https://github.com/lavalink-devs/Lavalink/discussions/1100" target="_blank">
    ⚠️ Lavalink V3 support ended - Nov 1, 2024. Prepare! Read more →
</Link></Banner>;
const navbar = (
    <Navbar
        logo={(
            <>
                <img src="/logo.svg" alt="logo" width="20" height="20"/>
                <span style={{marginLeft: '.4em', fontWeight: 800}}>
        Riffy
      </span>
            </>
        )}
        // ... Your additional navbar options
    />
);
const footer = <Footer>MIT {new Date().getFullYear()} © <a href="" target="_blank">Riffy.</a></Footer>;

export default async function RootLayout({children}) {
    return (
        <html
            // Not required, but good for SEO
            lang="en"
            // Required to be set
            dir="ltr"
            // Suggested by `next-themes` package https://github.com/pacocoursey/next-themes#with-app
            suppressHydrationWarning
        >
        <Head
            // ... Your additional head options
            color={{
                hue: 50
            }}
        >
            {/* Your additional tags should be passed as `children` of `<Head>` element */}
        </Head>
        <body>
        <Layout
            banner={banner}
            navbar={navbar}
            pageMap={await getPageMap()}
            docsRepositoryBase="https://github.com/riffy-team/riffy-docs/tree/main"
            footer={footer}
            sidebar={{ defaultMenuCollapseLevel: 2 }}
            // ... Your additional layout options
        >
            {children}
        </Layout>
        </body>
        </html>
    );
}
